name: Tests

on:
  pull_request:
  push:

jobs:
  shell-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run tests
        run: ./tests/sh/run-all.sh
  php-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'

      - name: Run PHP tests
        run: ./tests/php/run-all.sh

